quarkus.http.auth.permission.all-resources.paths=/*
quarkus.http.auth.permission.all-resources.policy=authenticated
quarkus.oidc.application-type=web-app
quarkus.oidc.logout.path=/logout
quarkus.http.port=8080
org.acme.users.ReservationsClient/mp-rest/url=http://localhost:8081
