greeting=Hello from Quarkus REST
quarkus.http.port=8085
quarkus.test.continuous-testing=enabled
%test.quarkus.oidc.enabled=false # to avoid slowing down test execution unnecessarily since the project's tests don't touch Keycloak
