greeting=Hello configuration
quarkus.oidc.enabled=false # because no docker daemon is used in my local atm
%test.quarkus.oidc.enabled=false # to avoid slowing down test execution unnecessarily since the project's tests don't touch Keycloak
