quarkus.http.port=8081
quarkus.http.test-port=8181
quarkus.swagger-ui.enable=true
org.acme.reservation.rental.RentalClient/mp-rest/url=http://localhost:8082
quarkus.smallrye-graphql-client.inventory.url=http://localhost:8083/graphql
quarkus.test.continuous-testing=enabled
