quarkus.http.port=8081
quarkus.http.test-port=8181
quarkus.swagger-ui.enable=true
org.acme.reservation.rental.RentalClient/mp-rest/url=http://localhost:8082
quarkus.smallrye-graphql-client.inventory.url=http://localhost:8083/graphql
quarkus.test.continuous-testing=enabled
quarkus.oidc.application-type=service
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=user
quarkus.datasource.password=pass
# drop and create the database at startup
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
# intentionally defines connection URL only in prod mode to allow Dev services
%prod.quarkus.datasource.reactive.url=vertx-reactive:postgresql://localhost:5432/reservation
%prod.quarkus.oidc.auth-server-url=http://localhost:7777/realms/car-rental
%prod.quarkus.oidc.client-id=reservation-service
%prod.quarkus.oidc.token-state-manager.split-tokens=true
%dev.quarkus.hibernate-orm.dev-ui.allow-hql=true
mp.messaging.incoming.invoices-rabbitmq.queue.name=invoices
mp.messaging.incoming.invoices-rabbitmq.exchange.name=invoices
